spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false


mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath*:mappers/*.xml
